fwup-home/fwup

src/fwup.c
src/mmc.c
src/mmc.h

If fwup cannot unmount a partition it will still display the umount error message, but will no longer exit.

Ignore errors if unmount fails

---

src/fatfs.c

I ended up with a kernel that was too large for the fat partition in my fwup.conf. The error message just said "Error writing file to FAT" and it took a fair bit of debugging to figure out what was actually happening (because I'm a noob :D). This adds a bit of useful information to the error message. My big kernel now gives the error: "fwup: Error writing file to FAT: zImage, expected 96590 bytes written, got 79944 (maybe the disk is full?)"

Adding more detail to error message

---

src/cfgfile.h
src/mmc.h
src/util.h

<sys/types.h> is needed for the definition of off_t, otherwise building
with uClibc fails with:
In file included from cfgfile.c:17:0:
cfgfile.h:25:87: error: unknown type name ‘off_t’
int archive_read_all_data(struct archive *a, struct archive_entry *ae, char **buffer, off_t max_size, off_t *size_read);
^
cfgfile.h:25:103: error: unknown type name ‘off_t’
int archive_read_all_data(struct archive *a, struct archive_entry *ae, char **buffer, off_t max_size, off_t *size_read);
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>

Add missing <sys/types.h> includes

---

.gitignore
autogen.sh

Using the autogen.sh script should not be mandatory, using autoreconf
directly should also be possible, and is actually done by numerous
embedded Linux build systems.
Signed-off-by: Thomas Petazzoni <thomas.petazzoni@free-electrons.com>

m4: add directory needed for autoreconf to succeed

---

src/mmc_windows.c
src/util.c

In Windows, a LogicalVolume is a partition or collection of disks (e.g. a RAID group) that has a drive letter. I think what fwup would want to write to is the raw disk itself, which is a PhysicalDrive.
These are conveniently numbered from 1 to N as they are enumerated by the system. Unfortunately, there's not a reliable API to tell you which ones exist. They can disappear (e.g. by unplugging a USB device), leaving a gap in the sequence, as the higher-numbered PhysicalDrives are not re-numbered.
This implementation simply walks across the numbered drives until it finds 5 in a row that are invalid (do not exist). This eliminates the need to assume there won't be more than N drives and checking that many, and would only cause trouble if someone plugged in more than 5 card readers and then …

Enumerate PhysicalDrives instead of LogicalVolumes on Windows

---

docs/build_linux.md

Without zip installed the following tests will fail:
* 015_fat_bad_sha2.test
* 016_raw_bad_sha2.test
* 047_unknown_apply_succeeds.test

Add zip to common dependencies

---

src/util.h

Fixes the prefix so that it patches the docs. I think WN is better than WA. Thoughts?

fix warning to be WN

---

src/sparse_file.h

Without sys/types.h the build breaks with errors like this:
parse_file.h:28:5: error: unknown type name ‘off_t’
off_t *map;
^

Fix uclibc build

---

docs/build_linux.md

I had to call `./scripts/build_deps.sh` before the `./configure` step was satisfied.

Add missing build_deps.sh step to docs for static build on Linux

---

3rdparty/base64.c
3rdparty/base64.h
CHANGELOG.md
README.md
fwup.pro
src/Makefile.am
src/fwup.c
src/fwup_genkeys.c
tests/021_create_keys.test
tests/131_raw_key.test
tests/132_key_as_param.test
tests/Makefile.am

This add support for passing signing keys around as text (base64-encoded) so that keys may more easily be stored as strings in code and environment variables on CI servers. This also adds commandline argments (`--public-key` and `--private-key`). This change removes the need to create temporary key files. Obviously, the standard care still needs to be taken when passing private keys in using this mechanism so that they don't appear in publicly viewable logs. The expected use for this is to sign firmware on CI servers where the private key is stored in an environment variable.

Base64 encode signing keys and support passing keys in via commandline

---

scripts/ChocolateyInstall.ps1
scripts/ChocolateyUninstall.ps1
scripts/build_pkg.sh
scripts/fwup

This reverts commit f51a8067daec6a6c8d79cb4e76af453f58b46b8e.
The fwup shell script breaks the chocolately packaging.

Revert "Add fwup shell wrapper"

---

src/mmc_linux.c

Future glibc releases won't include sysmacros implicitly anymore and will
fail with errors like:
```
fwup-mmc_linux.o: In function `mmc_is_path_at_device_offset':
mmc_linux.c:(.text+0x478): undefined reference to `minor'
mmc_linux.c:(.text+0x485): undefined reference to `major'
collect2: error: ld returned 1 exit status
```

src/mmc_linux.c: Include <sys/sysmacros.h>

---

src/fatfs.c

When switching partition the last segment from the last file will not be written. This is demonstrated with the attached files. test.img is made with the old version and test2.img with the new. At address 0xC9F4 the file "pi3-miniuart-bt.dtbo" is cut off in test.img.
[fwup.tar.gz](https://github.com/fhunleth/fwup/files/2242779/fwup.tar.gz)
The only necessary change for my case is the one in fatfs_truncate(). But I think the other changes are necessary to avoid other bugs.
My change sees to that the old file is closed before closing the old file system in MAYBE_MOUNT().

Fixed a bug where the last bytes of files where not written when changing partition.

---

src/cfgfile.c
src/fwup_genkeys.c

Fix build errors:
- Include error in src/cfgfile.c
- PATH_MAX is not defined in fwup_genkeys.c
Errors occurs when build for rpi0w by yocto

Fix: build error

---

img2fwup

Yocto found this.  We are using `/bin/bash` currently when only `/bin/sh` is really needed.

Only /bin/sh is needed for img2fwup

---

Makefile.am
configure.ac

Scripts like img2fwup aren't needed on the embedded side, so offer an
option to not install them:
./configure --disable-scripts

Add option to ./configure to not install scripts

---

src/block_cache.c
src/block_cache.h
src/fwup.c
src/fwup_apply.c
src/fwup_apply.h
src/mbr.c
src/mmc.h
src/mmc_bsd.c
src/mmc_linux.c
src/mmc_osx.c
src/mmc_windows.c

This doesn't work on OSX and prevents "expand=true" from expanding a
partition to fill the device. To work around this, move the device size
determination to platform-specific code.
Fixes #100.

Don't rely on lseek for device size

---

README.md
src/util.c
tests/162_source_date_epoch.test
tests/Makefile.am

This adds support for handling the $SOURCE_DATE_EPOCH environment
variable and documents how it can be used for reproducible builds.
See https://reproducible-builds.org/

Support SOURCE_DATE_EPOCH for reproducible builds

---

src/fwup.c
tests/166_gpt_expand-generate.sh
tests/166_gpt_expand.test

If the destination is not a multiple of 128 KB, it's possible to write
beyond the end since fwup writes in 128 KB blocks. This reduces the
destination length to the nearest multiple so that that can't happen.
This fixes an issue where writing the secondary GPT partition would fail
due to the added padding in the final block. Unfortunately, for drives
that are not a multiple of 128 KB, the secondary GPT is non-compliant
since it's not at the last block. I would assume that whatever logic
recovers from a corrupt primary GPT won't work since the GPT header
won't be at the expected LBA.
This should be fixed. However, as a minor consolation, manufactoring
Flash programmers typically take image files as input where the size of
the image is much less than the destination Flash size. The …

Account for 128 KB writes for final size

---

src/util.c
src/util.h

This removes an issue where you'd accidentally not specify enough
characters and get zeros filled in at the end. This only affects MBR
bootstrap binaries.

Force exact size for hex decoding

---

README.md
src/disk_crypto.c
tests/171_disk_crypto_aes_cbc_plain_deprecated.test
tests/Makefile.am

This matches how keys are passed to dm-crypt and makes it less
cumbersome to handle keys.
UPDATE: The original commit was a breaking change. That's been fixed. Base64 is still supported.

Switch disk encryption key to hex encoded

---

.travis.yml
README.md
configure.ac
scripts/build_and_test_minimal.sh
scripts/ci_build.sh
scripts/ci_install_deps.sh
src/fwfile.c
src/fwup.c
src/fwup_create.c
src/fwup_genkeys.c
src/fwup_sign.c
src/sparse_file.c

This change makes it possible to trim down the footprint of fwup. This
primarily removes the capability of creating firmware archives since
that is almost never used on devices.
To use:
```sh
./configure --enable-minimal-build.
```
Note that the regression tests will fail since archives can't be
created. The solution to this is to build a full-featured and minimal
version of fwup and use the full-featured one to create the archives.
See the `build_and_test_minimal.sh` script for details.

Support building minimal versions of fwup

---

README.md
src/cfgfile.c
tests/090_sparse_write.test
tests/091_sparse_write2.test
tests/092_sparse_write3.test
tests/093_sparse_concat.test
tests/094_sparse_concat2.test
tests/150_no_sparse.test

Fwup has a feature where it can respect sparse file holes and recreate
them on devices. This can majorly save time writing large ext2/4
partitions to Flash. It has a couple gotchas that make it tricky to use:
1. If programs creating the sparse files create holes to initialize runs
of zeros, those holes may not contain zeros on the device. It would be
nice if the programs wrote zeros, but that can't be enforced.
2. Sparse hole sizes and offsets depend on the filesystems where the
archives are created. This introduces another variation when trying
make reproducible builds.
3. Sparse files are incompatible with the upcoming binary delta feature.
In other words, any files that are stored as sparse ones cannot be
turned into patches.
Since sparse file reproduction is an optimization, it was …

Change the skip-holes default to off

---

src/archive_open.c
src/archive_open.h
src/cfgfile.c
src/fwup_apply.c
src/fwup_verify.c
src/progress.c
src/progress.h
tests/020_normal_progress.test
tests/104_info_msg.test
tests/141_exit_handshake.test

The progress bar still moves based on output written since that's
more correlated with the update duration. However, it wasn't obvious
that the firmware update sizes were almost always much smaller than what
was written. This makes it more obvious and seems like useful status.

Update progress bar to report input processed

---

tests/176_newline_in_key.test
tests/Makefile.am

It appears that issue #120 was already fixed. This adds a unit test to
make sure that it doesn't come back.

Verify that whitespace in keys is handled

---

README.md
src/cfgfile.c
src/gpt.c
src/progress.c
tests/177_gpt_boot_flag-generate.sh
tests/177_gpt_boot_flag.test
tests/178_gpt_bad_flags.test
tests/Makefile.am

Now instead of `flags=0x4`, you can specify `boot=true`. To ensure that older versions of fwup will still work with new files, if `boot=true`, the `flags` field is updated when stored in the `.fw` file.
Fixes #132

Add boot convenience flag for GPT partitions

---

src/block_cache.c
src/block_cache.h
src/fwup_apply.c
tests/117_on_error.test

Previously, there was an attempt to flush inflight writes when errors
occur. This stops this from happening. I.e., any error will stop all writes
that fwup still has not issued to the OS.
The reason for this change is that if a write error occurs, the call to
flush could result in another error that would be reported to users instead
of the original one. The first one was closer to the root cause and more
helpful when debugging.
Also, I have a different opinion now with fwup and writes after errors. I
believe that my previous logic for flushing is wrong, and the simplest
course of action is for fwup to stop as soon as an unrecoverable error has
been hit.

Quick fail on any write error

---

configure.ac
tests/029_5G_offset.test
tests/030_2T_offset.test
tests/031_fat_mkfs_5G.test
tests/032_fat_2T_offset.test
tests/090_sparse_write.test
tests/091_sparse_write2.test
tests/092_sparse_write3.test
tests/093_sparse_concat.test
tests/094_sparse_concat2.test
tests/105_require_path_on_device.test
tests/111_streaming_exit_fast.test
tests/130_media_sizes.test
tests/134_pipe_write_file.test
tests/145_require_path_at_offset.test
tests/150_no_sparse.test

It turns out that 77 is the magic exit code to indicate this.

Mark skipped tests in results

---

src/fwup_apply.c

Even if it's not null, the filename seems obvious, so just leave it off.

Don't print filename since it can be null

---

src/fwup.c
src/mmc.h
src/mmc_bsd.c
src/mmc_linux.c
src/mmc_osx.c
src/mmc_windows.c

These are getting popular, so allow them to be autodetected now.
The downside is that anyone with a 128 GiB drive on a platform where
`fwup` can't detect whether it's nonremovable will have to be more
careful. Hopefully that's not very common among `fwup` users.

Autodetect 128 GiB SDCards

---

docs/build_windows.md

I have successfully built `fwup` and `fwup.*.nupkg`. Some description should be added to the build steps.
- Add Ubuntu20/WSL2 as the environment that works well to build
- `zip` and `xdelta3` are needed to pass the test-suite.
- Setting `$DISPLAY` may be needed to avoid an error about `Wine Mono is not installed`. This error may appeared when we use Wine Mono on Linux at the first time.
- Add some sections to make it easier to understand.

Build on WSL 2 works well

---

.travis.yml

Building with Ubuntu 20.04 ended up creating packages that had minimal
glibc requirements that forced users to update. This wasn't necessary,
so change the default version of Ubuntu back to the way it was before
the Windows updates.

Only build for windows with Ubuntu 20.04

---

README.md

The Web site of libconfuse has moved to https://github.com/libconfuse/libconfuse from https://www.nongnu.org/confuse/ .
> The libConfuse project has moved to github. You are being redirected automatically.
[libConfuse](https://www.nongnu.org/confuse/)

Change the URL of the Web site of libconfuse

---

src/fatfs.c

The redundant FAT is stored right after the first FAT and not at the end
like the comment says. This means that there's no reason to treat the
final blocks as special since it wouldn't be an optimization.

Fix incorrect stream setting; comment

---

scripts/ci_install_deps.sh
tests/011_fat_setlabel.test
tests/032_fat_2T_offset.test
tests/074_fat_cache_fail.test
tests/common.sh

This uses dosfstools on OSX if it's available since it does more checks
and catches issues that the OSX fsck_msdos misses. It also adds the `-n`
flag to avoid interactive mode.

Tests: use dosfstools on OSX; add -n to fsck.fat

---

tests/011_fat_setlabel.test
tests/032_fat_2T_offset.test
tests/074_fat_cache_fail.test

See the commits for the issue with the new dosfstools 4.2 label check. This PR
works around the issue since fixing it in FatFS looks riskier than keeping the
current behavior.

Work around dosfstools 4.2's FAT label check

---

README.md

Make the link name match the link so that user's don't get potentially
confused and use the outdated The https://aur.archlinux.org/packages/fwup/
package instead.

Update readme to point to fwup-git for arch linux

---

README.md
src/fwup.c
src/fwup_metadata.c
src/fwup_metadata.h
tests/190_one_metadata_cmdline.test

Even though it's possible to use sed and awk to grab the metadata items
you want in shell scripts, it's annoying to do this and unescape quotes,
etc. This change adds the `--metadata-key` option. Here's an example:
```sh
$ fwup -m -i fwup.fw --metadata-key meta-uuid
ded51581-3c37-5dd5-d1b6-cd8503e4cfc4
```

Add --metadata-key to simplify getting one metadata value

---

docs/build_linux.md

This is needed or all of the tests that run `fsck.fat` will fail.
See #181.

Add dosfstools to Linux install docs for tests

---

README.md

Several tests failed with `xdelta3 undefined`, specifically tests 172, 173, 174 iirc. This PR updates the README to note that Arch users may need this package installed

Update README, Arch needs xdelta3

---

src/functions.c
src/uboot_env.c
src/uboot_env.h
tests/124_uboot_bad_param.test

Previously each U-Boot operation counted as 512 bytes. Now they count as
the full environment block. Even though byte count reports are arbitrary
due to caching, this fixes some weirdness with seeing 128KB U-Boot
environment block operations get reported as surprisingly small.
This also reduces some duplication of code and adds a few more tests to
make sure that a common mistake is reported nicely.

Improve progress reporting for u-boot operations

---

src/mmc_linux.c

This header file doesn't appear to be needed. This also fixes a build
error with glibc 2.36.
See
https://sourceware.org/glibc/wiki/Release/2.36#Usage_of_.3Clinux.2Fmount.h.3E_and_.3Csys.2Fmount.h.3E
for more information about the issue.
Fixes #192

Remove linux/fs.h include

---

README.md

fwup-git's dependencies are now up to date, so AUR users should no longer need to manually install xdelta3 before buliding.

update readme, fwup-git updated with proper deps

---

README.md
src/fwup.c
src/util.c
src/util.h
tests/133_path_write_file.test
tests/134_pipe_write_file.test

When exclusively using path_write and pipe_write, there's no need for a
destination image. Fwup really expects one so to tell it that you really
don't want one, pass `-d /dev/null`.
Fixes https://github.com/fwup-home/fwup/issues/200. See the issue for
more discussion.
Thanks to Edoardo Rossi for raising the need and also for supply the
patch to add it.

Allow /dev/null to be specified when no device is needed

---

tests/179_verify_detects_raw_corruption.test
tests/180_verify_detects_fat_corruption.test

It turned out that the bit being flipped was in a big block of zeros. It
probably doesn't make a difference for the point of the test, but
putting it in a real data block seems better.

Fix FAT corruption test to actually corrupt the table

---

README.md
src/functions.c
tests/192_resource_group.test
tests/194_implicit_fat_write.test
tests/Makefile.am

This is needed to support the file resources being automatically added.
The nice part is that since it creates backwards compatible archives, it
can be used as a convenience in newer fwup.conf files.
For example, before you'd have to write:
```
on-resource my_file.bin {
fat_write(\${BOOT_PART_OFFSET}, "my_file.bin")
}
```
Now you only have to specify `my_file.bin` once:
```
on-resource my_file.bin {
fat_write(\${BOOT_PART_OFFSET})
}
```
This works for directories too so long as the resource has the directory
name in it.

Use resource name when fat_write's filename isn't specified

---

README.md
src/block_cache.c
src/block_cache.h
src/fwup.c
src/fwup_apply.c
src/fwup_apply.h
tests/195_minimize_writes.test
tests/Makefile.am

This option currently defaults to off.
By passing --minimize-writes, fwup will read a block before writing it.
If the block is unchanged, the write is skipped entirely. This is
desirable if you're really interested in minimizing write operations to
Flash memory. Reasons include Flash being slow and it's common to be
rewriting similar data, worry about wearing Flash out prematurely, and
general worry that each write has a small chance to fail.

Add --minimize-writes option

---

src/block_cache.c
src/block_cache.h
src/functions.c
src/fwup.c
tests/160_mbr_expand.test
tests/166_gpt_expand.test
tests/196_small_destination.test
tests/197_fractional_end_segment.test
tests/198_gpt_partial-generate.sh
tests/198_gpt_partial.test
tests/Makefile.am

There was a constraint that would round the destination to a multiple of
128KB segments so that <128KB writes didn't need to be handled. These
are now handled, but only for the very last 128KB segment.
A --max-size option was added to make testing this feature possible on
regular files. For real devices, the max size is automatically
determined from the device. This option can reduce the max size of a
real device.
Internally, the variable tracking the max size (end_offset) is now a
hard limit. It used to be a soft limit so that it was possible to infer
a good guess from a regular file. That was interesting for testing MBR
and GPT functionality, but not really anywhere else. The hard limit
makes it possible calculate the partial write size at the end of the
device and to give a better …

Support partial final writes and add --max-size option

---

src/block_cache.c
tests/198_gpt_partial-generate.sh
tests/198_gpt_partial.test
tests/199_partial_read.test
tests/Makefile.am

This adjusts the generation script to add some padding that's not in any
partition to push the secondary header into a partial final segment.
This is a better test since it exercises fwup's GPT secondary header
placement code in a more obvious way. The test came too close to working
without the partial final segment commit for comfort.

Improve GPT test with partial final segment

---

tests/011_fat_setlabel.test
tests/066_fat_attrib.test
tests/156_fat_truncation_bug.test

mtools utilities now output underscores when `LC_ALL` is set to show you
hidden spaces in names. This is helpful, but breaks the unit tests.
Since it just seems to be in the latest mtools versions, turn it off by
unsetting `LC_ALL`.

Fix test failures using mtools

---

src/mmc.h
src/mmc_bsd.c
src/mmc_linux.c
src/mmc_osx.c

The size is set to 1 MiB, so it's much smaller than any use of fwup that
I've seen. It will help reduce false positives from devices that have
docs on a small read-only drive.
Fixes #222

Do not autodetect very small drives

---

tests/175_sign_delta_upgrade.test
tests/201_sign_delta_upgrade2.test
tests/Makefile.am

This addresses the regression caught by test 175. It doesn't fix it, but
includes a link to the tracking issue and adds a test to add more confidence
that the regression doesn't affect production.
- **Explicitly test signed delta updates**
- **Add prints to test 175 to make verify failures easier to identify**
- **Comment out the failing call to verify in test 175**

Isolate test 175 failure; explicitly verify signed deltas

---

src/fwup.c
tests/160_mbr_expand.test
tests/166_gpt_expand.test
tests/172_delta_upgrade.test
tests/174_streamed_delta_upgrade.test
tests/192_delta_out_of_bound.test
tests/201_sign_delta_upgrade2.test

This makes writing external media and regular files work more similar.
Automatic size checks were never hooked up for regular files even though 
this is a very convenient use case when using Qemu. This change 
implements it.
The way this works is that Qemu users first create a disk image. This is
just a big sparse file and then they run fwup to program the initial
image. The disk image size will be total image size in this case, so the
expansion and end-seeking functionality is expected to work.
When the destination file does not exist or is 0, fwup works as it
previously does by only writing the minimum size possible or following
the `--max-size` commandline argument.
IMPORTANT: Regular files no longer automatically expand if they're
nonzero in size. This can break test scripts, but if …

When writing regular files, check file size to support expansion

---

src/fwup_create.c

Changes formatting for `assert-size-lte` and `assert-size-lte` error messages. When working with file sizes over 2GB, you can no longer use a signed 32bit int for display as it will show incorrect values

display output with unsigned longs

---

README.md
src/3rdparty/fatfs/source/ffconf.h
src/fatfs.c
src/fatfs.h
src/functions.c
tests/203_multi_fat.test
tests/204_fat_cp_cross_partition.test
tests/Makefile.am

This has two commits. The first is to enable multiple FAT partitions being
"mounted" at once. The second adds the 4-arg version of fat_cp to copy across
two partitions.
The motivation for this is to support a Raspberry Pi use case where the
bootloader needed to be copyied to two FAT partitions.
- **Reduce thrashing when writing multiple FAT filesystems**
- **Extend fat_cp to copy between FAT filesystems**

Support copying between FAT partitions

---

src/fwup_apply.c
src/mbr.c
src/mbr.h
src/requirement.c

This cleans up all of the magic number 4s everywhere, but the main goal
is to be a step in the direction of MBR extended partition support.

Collect MBR table information in one struct

---

README.md
src/cfgfile.c
src/functions.c
src/functions.h
src/fwup.c
src/fwup_apply.c
src/fwup_apply.h
tests/209_reboot_param.test
tests/Makefile.am

This function influences the reboot call that's normally run after an
update. This is useful for Raspberry Pi devices that need to pass `"0
tryboot"` to reboot on updates.

Add reboot-param function

---

configure.ac
src/mmc_linux.c
tests/210_new_require_path.test
tests/211_new_require_path_dm.test
tests/Makefile.am
tests/common.sh
tests/fixture/.gitignore
tests/fixture/Makefile.am
tests/fixture/mount_shim.c

This makes it possible to detect the physical block device that the root
filesystem uses even if Linux's device mapper is being used for
encrypted partitions or overlays or anything else.

Support the use of device mapper for root filesystem mounts

---

README.md
src/util.c
src/util.h

The use of this message for actual warnings is so rare that saying it is
a warning is misleading. This message comes from calls to info() in
fwup.conf files nearly all of the time.
This changes the docs, but not the letters used for the message so
there's no concern about backwards compatibility.

Change docs for streaming WN message to indicate info

---

src/block_cache.c
src/block_cache.h
src/fwup.c
src/fwup_apply.c
src/fwup_apply.h
tests/214_expand_afterwards.test
tests/Makefile.am

Regular files worked differently depending on whether fwup was run to
create an image file or to modify an image file. When creating the file,
the fwup instructions could expand it as much as disk space allowed.
However, when modifying the file, fwup limited the max length to the
existing length or whatever was passed on the command line.
This commit adds the concept of a soft limit when modifying existing
files. This soft limit can be bumped when writing, but gets used when
expanding partitions to fill space.
Fixes the cause of the error in #253. The hang won't happen, but the next PR will fix the hang that blocked the error.

Support soft limits for regular files

---

src/fwup_xdelta3.c
src/fwup_xdelta3.h
tests/216_delta_progress.test
tests/Makefile.am

This removes the constraint where progress reporting was based on xdelta3's window size configuration. By default, this was 8 MB which resulted in 8 MB being returned on every call. Since 8 MB actually took quick a bit of time to accumulate and write, it led to the progress bar sticking for 30-60 seconds or more. This was quite unsettling to say the least.
This change returns a maximum of 128 KB chunks at a time which matches other write buffering sizes, so it hopefully is a happy medium of allowing efficient write block sizes while allowing the code to return to do the writes and report progress.

Return smaller chunks at a time with deltas
